const LOGIN_STARTED = 'LOGIN_STARTED';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_UNSUCCESS = 'LOGIN_UNSUCCESS';

const SELECT_USER = 'SELECT_USER';

const SUBSCRIBE_ACCEPTED = 'SUBSCRIBE_ACCEPTED';
const NEW_COMMENT = 'NEW_COMMENT';
const REQUEST_SUBSCRIBE = 'REQUEST_SUBSCRIBE';

export {
    LOGIN_STARTED, 
    LOGIN_SUCCESS,
    LOGIN_UNSUCCESS,
    SELECT_USER,
    SUBSCRIBE_ACCEPTED,
    NEW_COMMENT,
    REQUEST_SUBSCRIBE 
}